/**
 * First-launch screen — pair this register with a store.
 *
 * Default flow: 6-digit pairing code generated by the owner from
 * /dashboard/devices on Store Ops. Identity chain ends at a Passport user
 * via the RegisterDevice row created server-side.
 *
 * Advanced flow (kept for headless tooling and pre-pairing-flow keys):
 * paste an `ar_live_*` API key + store ID directly. Same X-API-Key
 * header, different lifecycle.
 *
 * Once setup completes, this screen never shows again unless the device
 * is reset from Settings.
 */

import { useState } from "react";
import {
  setServerConfig,
  setTaxSettings,
  setStripePublishableKey,
  setTapToPayApproved,
  getDeviceId,
} from "../device";
import { fetchBootstrap, pairDevice } from "../api";
import { replaceInventory, replaceStaff } from "../db";
import { Screen, Button, Input, Card, H1, H2, Muted, colors } from "../ui";
import type { ServerConfig } from "../types";

const DEFAULT_BASE = "https://www.afterroar.store";

type Mode = "code" | "key";

export function Setup({ onDone }: { onDone: () => void }) {
  const [mode, setMode] = useState<Mode>("code");
  const [busy, setBusy] = useState(false);
  const [error, setError] = useState<string | null>(null);

  // Pairing-code mode state
  const [code, setCode] = useState("");
  const [deviceName, setDeviceName] = useState("");

  // API-key mode state (advanced)
  const [apiKey, setApiKey] = useState("");
  const [storeId, setStoreId] = useState("");
  const [apiBase, setApiBase] = useState(DEFAULT_BASE);

  async function persistAndBootstrap(token: string, store: { id: string }, base: string) {
    await setServerConfig({ apiKey: token, storeId: store.id, apiBaseUrl: base });
    const cfg: ServerConfig = {
      apiKey: token,
      storeId: store.id,
      apiBaseUrl: base,
      deviceId: await getDeviceId(),
    };
    const data = await fetchBootstrap(cfg);
    await replaceInventory(data.inventory);
    await replaceStaff(data.staff);
    await setTaxSettings({
      ratePercent: data.store.taxRatePercent,
      includedInPrice: data.store.taxIncludedInPrice,
    });
    await setStripePublishableKey(data.store.stripePublishableKey);
    await setTapToPayApproved(data.store.tapToPayApproved);
  }

  async function handlePairByCode() {
    if (!/^\d{6}$/.test(code)) {
      setError("Code must be 6 digits.");
      return;
    }
    setBusy(true);
    setError(null);
    try {
      const deviceId = await getDeviceId();
      const result = await pairDevice(DEFAULT_BASE, {
        code,
        deviceId,
        displayName: deviceName.trim() || undefined,
      });
      await persistAndBootstrap(result.token, result.store, DEFAULT_BASE);
      onDone();
    } catch (err) {
      setError(err instanceof Error ? err.message : "Pairing failed.");
    } finally {
      setBusy(false);
    }
  }

  async function handleSubmitKey() {
    if (!apiKey.trim() || !storeId.trim()) {
      setError("API key and store ID are required.");
      return;
    }
    setBusy(true);
    setError(null);
    try {
      const base = apiBase.trim() || DEFAULT_BASE;
      await persistAndBootstrap(apiKey.trim(), { id: storeId.trim() }, base);
      onDone();
    } catch (err) {
      setError(err instanceof Error ? err.message : "Setup failed.");
    } finally {
      setBusy(false);
    }
  }

  return (
    <Screen>
      <div style={{ marginBottom: "1.5rem" }}>
        <H1>Set up this register</H1>
        <Muted style={{ marginTop: "0.25rem" }}>
          One-time setup. Get a pairing code from your owner — sign-in is handled by Passport on their end.
        </Muted>
      </div>

      {mode === "code" ? (
        <>
          <Card style={{ display: "flex", flexDirection: "column", gap: "0.75rem" }}>
            <label>
              <Muted>Pairing code (6 digits)</Muted>
              <div style={{ marginTop: "0.5rem" }}>
                <input
                  inputMode="numeric"
                  autoFocus
                  maxLength={6}
                  value={code}
                  onChange={(e) => setCode(e.target.value.replace(/\D/g, "").slice(0, 6))}
                  placeholder="123456"
                  style={{
                    width: "100%",
                    boxSizing: "border-box",
                    padding: "1rem",
                    background: "rgba(0,0,0,0.3)",
                    border: `1px solid ${colors.rule}`,
                    borderRadius: "0.5rem",
                    color: colors.cream,
                    fontSize: "2rem",
                    fontFamily: "monospace",
                    fontWeight: 800,
                    textAlign: "center",
                    letterSpacing: "0.4em",
                    outline: "none",
                  }}
                />
              </div>
            </label>
            <label>
              <Muted>Device name (optional)</Muted>
              <div style={{ marginTop: "0.25rem" }}>
                <Input
                  value={deviceName}
                  onChange={setDeviceName}
                  placeholder="Counter 1"
                />
              </div>
            </label>

            {error ? (
              <div style={{ color: colors.red, fontSize: "0.85rem", padding: "0.5rem 0" }}>
                {error}
              </div>
            ) : null}

            <Button onClick={handlePairByCode} disabled={busy || code.length !== 6} size="lg">
              {busy ? "Pairing…" : "Pair register"}
            </Button>
          </Card>

          <Card style={{ marginTop: "1.25rem" }}>
            <H2>How to get a code</H2>
            <Muted style={{ marginTop: "0.5rem", lineHeight: 1.5 }}>
              The owner signs in to{" "}
              <span style={{ color: colors.orange }}>afterroar.store/dashboard/devices</span>{" "}
              and clicks <strong>Pair new register</strong>. They'll see a 6-digit code that
              expires in 10 minutes — type it above. The device will appear in their list once paired.
            </Muted>
          </Card>

          <button
            type="button"
            onClick={() => { setMode("key"); setError(null); }}
            style={{
              background: "transparent",
              border: "none",
              color: colors.inkFaint,
              fontSize: "0.74rem",
              cursor: "pointer",
              alignSelf: "flex-start",
              padding: "1rem 0 0",
              textAlign: "left",
            }}
          >
            Advanced: paste an API key instead
          </button>
        </>
      ) : (
        <>
          <Card style={{ display: "flex", flexDirection: "column", gap: "0.75rem" }}>
            <label>
              <Muted>API key</Muted>
              <div style={{ marginTop: "0.25rem" }}>
                <Input value={apiKey} onChange={setApiKey} placeholder="ar_live_…" autoFocus />
              </div>
            </label>
            <label>
              <Muted>Store ID</Muted>
              <div style={{ marginTop: "0.25rem" }}>
                <Input value={storeId} onChange={setStoreId} placeholder="cmoegx80r000004i5ml460vn9" />
              </div>
            </label>
            <label>
              <Muted>API base URL</Muted>
              <div style={{ marginTop: "0.25rem" }}>
                <Input value={apiBase} onChange={setApiBase} placeholder={DEFAULT_BASE} />
              </div>
            </label>

            {error ? (
              <div style={{ color: colors.red, fontSize: "0.85rem", padding: "0.5rem 0" }}>
                {error}
              </div>
            ) : null}

            <Button onClick={handleSubmitKey} disabled={busy} size="lg">
              {busy ? "Setting up…" : "Bootstrap with key"}
            </Button>
          </Card>

          <button
            type="button"
            onClick={() => { setMode("code"); setError(null); }}
            style={{
              background: "transparent",
              border: "none",
              color: colors.inkFaint,
              fontSize: "0.74rem",
              cursor: "pointer",
              alignSelf: "flex-start",
              padding: "1rem 0 0",
              textAlign: "left",
            }}
          >
            ← back to pairing code
          </button>
        </>
      )}
    </Screen>
  );
}
